version: '3.8'

services:
  go-web-app:
    build: .
    ports:
      - "8086:8086"
    environment:
      - GO_ENV=production
    volumes:
      - ./templates:/root/templates
      - ./xsl:/root/xsl
      - ./fonts:/root/fonts
